apiVersion: apps/v1
kind: Deployment
metadata:
  name:  testo-bot
  namespace: bots
  labels:
    app: testo-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testo-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testo-bot
    spec:
      containers:
        - image: docker.pkg.github.com/dominikus1993/testo-discord-bot/testo-bot:latest
          name: testo-bot
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name:  bot-config 
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "128m"
      imagePullSecrets:
        - name: github